image:
- Visual Studio 2017

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  NEXTPNR_COMMIT: 79dbeda0f3b73d149fcd1f39cb7110cf6f8a6237
  NEXTPNR_URI: https://github.com/xobs/nextpnr.git
  VCPKG_COMMIT: 8900146533f8e38266ef89766a2bbacffcb67836
  PYTHON_URI: https://www.python.org/ftp/python/3.7.3/python-3.7.3-embed-amd64.zip
  matrix:
    # MSVC
    - TARGET: x86_64-pc-windows-msvc

install:
  - ps: |
      If ($Env:TARGET -eq 'x86_64-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw64\bin'
      } ElseIf ($Env:TARGET -eq 'i686-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw32\bin'
      }
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      cd C:\tools\vcpkg
      git rev-parse HEAD
      git checkout $env:VCPKG_COMMIT
      vcpkg integrate install
      vcpkg install boost-filesystem:x64-windows boost-program-options:x64-windows boost-thread:x64-windows boost-python:x64-windows eigen3:x64-windows
      cd C:\tools
      Invoke-WebRequest -uri $env:PYTHON_URI -OutFile C:\tools\python.zip
      [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\tools\python.zip", "C:\tools\Python")
      [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\tools\python\Python37.zip", "C:\tools\Python")

      cd $env:APPVEYOR_BUILD_FOLDER
      git clone $env:NEXTPNR_URI
      cd nextpnr
      git checkout $env:NEXTPNR_COMMIT

      [System.IO.Compression.ZipFile]::ExtractToDirectory("C:/tools/Python/python37.zip", "$($env:APPVEYOR_BUILD_FOLDER)\nextpnr\Lib")
      cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DARCH=ice40 "-DICEBOX_ROOT=$($env:APPVEYOR_BUILD_FOLDER.replace("\", "/"))/icebox" -DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 15 2017 Win64" -DPYTHON_EXECUTABLE=C:/tools/Python/python.exe -DBUILD_GUI=OFF .
      cmake --build . --config Release


      $SRC_DIR = "$($ENV:APPVEYOR_BUILD_FOLDER)\nextpnr"
      $stage_temp = [System.Guid]::NewGuid().ToString()
      $stage = "$($ENV:Temp)\$($stage_temp)"
      Set-Location $ENV:Temp
      New-Item -Type Directory -Name $stage_temp
      Set-Location $stage
      $zip = "$SRC_DIR\nextpnr-$($ENV:APPVEYOR_REPO_TAG_NAME)-windows_amd64.zip"
      Copy-Item "$SRC_DIR\Release\*.dll" '.\'
      Copy-Item "$SRC_DIR\Release\nextpnr-ice40.exe" '.\'
      $libdir = "$($stage)\Lib"
      [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\tools\python\Python37.zip", $libdir)
      [System.IO.Compression.ZipFile]::CreateFromDirectory($stage, $zip)
      Push-AppveyorArtifact "$zip"

      Remove-Item *.* -Force
      Set-Location ..
      Remove-Item $STAGE
      Set-Location $SRC_DIR

deploy:
  artifact: /.*\.zip/
  auth_token:
    secure: '3H1TyUJgA/HcXJaMa4cL9ZBICbnBt+lklIvehG6LRG71VbUn9uXNUNtTeCFJp5mh'
  description: 'Automated release'
  on:
    appveyor_repo_tag: true
  provider: GitHub

cache:
  - c:\tools\vcpkg\installed\

branches:
  only:
    # Release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  - provider: Email
    to:
      - sean@xobs.io
    on_build_status_changed: true
    on_build_success: false

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false